name: oldcrown
favicon: null
layout_spectrum: 0.97221
typography_spectrum: 0.07897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08091470040380955
  lightness: 0.34981834073551
  saturation: 0.05938308825716376
  rhythmicContrast: 0.001150886295363307
purpose: []
